import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar/Sidebar";
import SessionProvider from "@/components/common/SessionProvider"; //
import { auth } from "@/auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Instagram Clone",
  description: "Clone project generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider>
          <div className="flex h-screen w-full overflow-hidden bg-white">
            {/* 1. 사이드바 (fixed 포지션이므로 별도 공간 차지 X, 화면 위에 뜸) */}
            <Sidebar currentUser={session?.user} />
            {/* 2. 메인 콘텐츠 */}
            {/* ml-20: 사이드바 너비(w-20)만큼 왼쪽 여백을 줘서 겹치지 않게 함 */}
            <main className="flex-1 ml-20 overflow-y-auto">{children}</main>
          </div>
        </SessionProvider>
      </body>
    </html>
  );
}
