import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* flex h-screen w-full: 화면 꽉 채우기 */}
        <div className="flex h-screen w-full overflow-hidden">
          
          {/* 사이드바 */}
          {/* border-r, bg-gray-50 제거함 -> 그냥 흰색 영역만 남음 */}
          <aside className="flex-none w-64">
            <Sidebar />
          </aside>

          {/* 메인 콘텐츠 */}
          <main className="flex-1 overflow-y-auto">
            {children}
          </main>
          
        </div>
      </body>
    </html>
  );
}
